2023-08-10 14:45:03,694 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 14:45:47,238 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "GET /ops/userGet/ HTTP/1.1" 200 2
2023-08-10 14:46:00,897 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "OPTIONS /ops/userAdd/ HTTP/1.1" 200 0
2023-08-10 14:46:00,961 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/userAdd/ HTTP/1.1" 200 48
2023-08-10 14:54:37,087 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 14:55:08,516 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 14:55:57,080 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/userAdd/ HTTP/1.1" 200 48
2023-08-10 14:56:18,175 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "GET /ops/userGet/ HTTP/1.1" 200 85
2023-08-10 15:22:14,185 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "GET /ops/nexusInfofile/ HTTP/1.1" 200 296
2023-08-10 15:22:14,266 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/nexusInfofile/ HTTP/1.1" 200 2
2023-08-10 15:22:15,388 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "GET /ops/nexusInfofile/ HTTP/1.1" 200 296
2023-08-10 15:22:15,449 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/nexusInfofile/ HTTP/1.1" 200 152
2023-08-10 15:22:16,366 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "GET /ops/nexusInfofile/ HTTP/1.1" 200 296
2023-08-10 15:22:16,433 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/nexusInfofile/ HTTP/1.1" 200 152
2023-08-10 15:22:16,821 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "GET /ops/nexusInfofile/ HTTP/1.1" 200 296
2023-08-10 15:22:16,940 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/nexusInfofile/ HTTP/1.1" 200 152
2023-08-10 15:26:09,554 [ERROR] /opt/microMonitor/lib/python3.10/site-packages/django/utils/log.py:224 Internal Server Error: /ops/mysqlInstall/
Traceback (most recent call last):
  File "/opt/microMonitor/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/microMonitor/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/python/django3ops/app/views.py", line 73, in mysql_install
    xx = Ssh(result).run_cmd('ls')
  File "/root/python/django3ops/utilitys/ssh.py", line 15, in __init__
    self.host = host_dict['host']
KeyError: 'host'
2023-08-10 15:26:09,556 [ERROR] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 500 67746
2023-08-10 15:26:49,503 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 15:26:58,180 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 200 15
2023-08-10 15:28:14,250 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 15:28:44,221 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 200 15
2023-08-10 15:29:09,666 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 15:29:14,032 [ERROR] /opt/microMonitor/lib/python3.10/site-packages/django/utils/log.py:224 Internal Server Error: /ops/mysqlInstall/
Traceback (most recent call last):
  File "/opt/microMonitor/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/microMonitor/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/python/django3ops/app/views.py", line 75, in mysql_install
    print(host_ip.hostip)
AttributeError: 'QuerySet' object has no attribute 'hostip'
2023-08-10 15:29:14,034 [ERROR] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 500 63919
2023-08-10 15:32:11,444 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 15:32:14,883 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 200 15
2023-08-10 15:32:46,412 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 15:32:49,182 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 200 15
2023-08-10 15:47:02,651 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "GET /ops/nexusInfofile/ HTTP/1.1" 200 296
2023-08-10 15:47:02,669 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "OPTIONS /ops/nexusInfofile/ HTTP/1.1" 200 0
2023-08-10 15:47:02,721 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/nexusInfofile/ HTTP/1.1" 200 2
2023-08-10 15:47:03,550 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "GET /ops/nexusInfofile/ HTTP/1.1" 200 296
2023-08-10 15:47:03,609 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/nexusInfofile/ HTTP/1.1" 200 152
2023-08-10 15:47:03,853 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "GET /ops/nexusInfofile/ HTTP/1.1" 200 296
2023-08-10 15:47:03,939 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/nexusInfofile/ HTTP/1.1" 200 152
2023-08-10 15:47:04,453 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "GET /ops/nexusInfofile/ HTTP/1.1" 200 296
2023-08-10 15:47:04,523 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/nexusInfofile/ HTTP/1.1" 200 152
2023-08-10 15:47:05,602 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "OPTIONS /ops/mysqlInstall/ HTTP/1.1" 200 0
2023-08-10 15:47:05,620 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 200 15
2023-08-10 15:50:15,652 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 15:50:17,669 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 200 15
2023-08-10 15:53:50,694 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 15:53:55,781 [ERROR] /opt/microMonitor/lib/python3.10/site-packages/django/utils/log.py:224 Internal Server Error: /ops/mysqlInstall/
Traceback (most recent call last):
  File "/opt/microMonitor/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/microMonitor/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/python/django3ops/app/views.py", line 75, in mysql_install
    combined_results = Assets.objects.filter(combined_query)
  File "/opt/microMonitor/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/microMonitor/lib/python3.10/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/opt/microMonitor/lib/python3.10/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/opt/microMonitor/lib/python3.10/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/opt/microMonitor/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1416, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/opt/microMonitor/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1435, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/opt/microMonitor/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1288, in build_filter
    return self._add_q(
  File "/opt/microMonitor/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1435, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/opt/microMonitor/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1309, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/opt/microMonitor/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1135, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/opt/microMonitor/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1562, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'assets' into field. Choices are: hostip, hostname, id, port
2023-08-10 15:53:55,807 [ERROR] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 500 120704
2023-08-10 16:13:51,698 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 16:14:02,070 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 200 15
2023-08-10 16:16:33,715 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 16:16:44,491 [ERROR] /opt/microMonitor/lib/python3.10/site-packages/django/utils/log.py:224 Internal Server Error: /ops/mysqlInstall/
Traceback (most recent call last):
  File "/opt/microMonitor/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/microMonitor/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/python/django3ops/app/views.py", line 77, in mysql_install
    combined_results = list(authors.update(asset))
TypeError: QuerySet.update() takes 1 positional argument but 2 were given
2023-08-10 16:16:44,493 [ERROR] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 500 65095
2023-08-10 16:17:31,465 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 16:17:35,207 [ERROR] /opt/microMonitor/lib/python3.10/site-packages/django/utils/log.py:224 Internal Server Error: /ops/mysqlInstall/
Traceback (most recent call last):
  File "/opt/microMonitor/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/microMonitor/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/python/django3ops/app/views.py", line 78, in mysql_install
    combined_results = list(authors.update(asset))
TypeError: QuerySet.update() takes 1 positional argument but 2 were given
2023-08-10 16:17:35,209 [ERROR] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 500 65073
2023-08-10 16:25:24,348 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 16:25:28,405 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 200 15
2023-08-10 16:38:00,773 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 16:38:06,742 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 200 15
2023-08-10 16:39:54,401 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 16:39:56,339 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 200 15
2023-08-10 16:40:17,277 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 16:40:20,295 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 200 15
2023-08-10 16:41:24,364 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 16:41:27,432 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 200 15
2023-08-10 16:42:25,908 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 16:42:29,533 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 200 15
2023-08-10 16:42:52,258 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 16:42:55,451 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 200 15
2023-08-10 16:43:21,636 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 16:43:23,490 [ERROR] /opt/microMonitor/lib/python3.10/site-packages/django/utils/log.py:224 Internal Server Error: /ops/mysqlInstall/
Traceback (most recent call last):
  File "/opt/microMonitor/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/microMonitor/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/python/django3ops/app/views.py", line 83, in mysql_install
    xx = Ssh(combined_results).run_cmd('ls')
  File "/root/python/django3ops/utilitys/ssh.py", line 38, in run_cmd
    ssh._transport = self.__transport
AttributeError: 'Ssh' object has no attribute '_Ssh__transport'
2023-08-10 16:43:23,492 [ERROR] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 500 69916
2023-08-10 16:51:48,456 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 16:51:53,526 [ERROR] /opt/microMonitor/lib/python3.10/site-packages/django/utils/log.py:224 Internal Server Error: /ops/mysqlInstall/
Traceback (most recent call last):
  File "/opt/microMonitor/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/microMonitor/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/python/django3ops/app/views.py", line 83, in mysql_install
    xx = Ssh(combined_results).run_cmd('ls')
  File "/root/python/django3ops/utilitys/ssh.py", line 38, in run_cmd
    ssh._transport = self._transport
AttributeError: 'Ssh' object has no attribute '_transport'
2023-08-10 16:51:53,529 [ERROR] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 500 69894
2023-08-10 16:55:51,224 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 16:55:55,779 [ERROR] /opt/microMonitor/lib/python3.10/site-packages/django/utils/log.py:224 Internal Server Error: /ops/mysqlInstall/
Traceback (most recent call last):
  File "/opt/microMonitor/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/microMonitor/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/python/django3ops/app/views.py", line 83, in mysql_install
    xx = Ssh(combined_results).run_cmd('ls')
  File "/root/python/django3ops/utilitys/ssh.py", line 38, in run_cmd
    ssh._transport = self.connect()
  File "/root/python/django3ops/utilitys/ssh.py", line 22, in connect
    transport = Transport((self.host, self.port))
  File "/opt/microMonitor/lib/python3.10/site-packages/paramiko/transport.py", line 442, in __init__
    sock.connect((hostname, port))
TypeError: 'str' object cannot be interpreted as an integer
2023-08-10 16:55:55,785 [ERROR] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 500 80398
2023-08-10 16:57:15,250 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 16:57:17,630 [ERROR] /opt/microMonitor/lib/python3.10/site-packages/django/utils/log.py:224 Internal Server Error: /ops/mysqlInstall/
Traceback (most recent call last):
  File "/opt/microMonitor/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/microMonitor/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/python/django3ops/app/views.py", line 83, in mysql_install
    xx = Ssh(combined_results).run_cmd('ls')
  File "/root/python/django3ops/utilitys/ssh.py", line 39, in run_cmd
    ssh._transport = self.connect()
  File "/root/python/django3ops/utilitys/ssh.py", line 23, in connect
    transport = Transport((self.host, self.port))
  File "/opt/microMonitor/lib/python3.10/site-packages/paramiko/transport.py", line 442, in __init__
    sock.connect((hostname, port))
TypeError: 'str' object cannot be interpreted as an integer
2023-08-10 16:57:17,633 [ERROR] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 500 80381
2023-08-10 16:57:43,510 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 16:57:45,166 [ERROR] /opt/microMonitor/lib/python3.10/site-packages/django/utils/log.py:224 Internal Server Error: /ops/mysqlInstall/
Traceback (most recent call last):
  File "/opt/microMonitor/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/microMonitor/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/python/django3ops/app/views.py", line 83, in mysql_install
    xx = Ssh(combined_results).run_cmd('ls')
  File "/root/python/django3ops/utilitys/ssh.py", line 39, in run_cmd
    ssh._transport = self.connect()
  File "/root/python/django3ops/utilitys/ssh.py", line 23, in connect
    transport = Transport((self.host, self.port))
  File "/opt/microMonitor/lib/python3.10/site-packages/paramiko/transport.py", line 442, in __init__
    sock.connect((hostname, port))
TypeError: 'str' object cannot be interpreted as an integer
2023-08-10 16:57:45,170 [ERROR] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 500 80375
2023-08-10 16:58:59,063 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 16:59:05,123 [ERROR] /opt/microMonitor/lib/python3.10/site-packages/django/utils/log.py:224 Internal Server Error: /ops/mysqlInstall/
Traceback (most recent call last):
  File "/opt/microMonitor/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/microMonitor/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/python/django3ops/app/views.py", line 83, in mysql_install
    xx = Ssh(combined_results).run_cmd('ls')
  File "/root/python/django3ops/utilitys/ssh.py", line 38, in run_cmd
    ssh._transport = self.connect()
  File "/root/python/django3ops/utilitys/ssh.py", line 23, in connect
    transport.connect(username=self.username, password=self.pwd)
  File "/opt/microMonitor/lib/python3.10/site-packages/paramiko/transport.py", line 1414, in connect
    self.auth_password(username, password)
  File "/opt/microMonitor/lib/python3.10/site-packages/paramiko/transport.py", line 1587, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "/opt/microMonitor/lib/python3.10/site-packages/paramiko/auth_handler.py", line 263, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.
2023-08-10 16:59:05,126 [ERROR] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 500 88153
2023-08-10 17:01:18,330 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 200 15
2023-08-10 17:27:01,298 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 17:27:08,419 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 200 15
2023-08-10 17:36:38,805 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 17:36:47,392 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 200 15
2023-08-10 17:38:23,167 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 17:39:03,044 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 200 15
2023-08-10 17:55:53,624 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 17:55:57,981 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "OPTIONS /ops/mysqlInstall/ HTTP/1.1" 200 0
2023-08-10 17:56:01,809 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 200 15
2023-08-10 17:56:57,450 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/utils/autoreload.py:637 Watching for file changes with StatReloader
2023-08-10 17:57:04,888 [INFO] /opt/microMonitor/lib/python3.10/site-packages/django/core/servers/basehttp.py:161 "POST /ops/mysqlInstall/ HTTP/1.1" 200 15
